language: perl
perl:
  - "5.8.4"
  - "5.14"
  - "5.20"
  - "5.24"
sudo: false
before_install:
  - git config --global user.name "TravisCI"
install:
  # Install local::lib so we don't have to run commands with sudo
   - cpanm --quiet --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  # Force install Text::Diff (5.8.x related)
   - cpanm --quiet --notest Text::Diff
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet
script:
  - dzil smoke --release --author
